"""YOLO label-file writer + small helpers."""

from __future__ import annotations

from pathlib import Path

YOLO_CLASS_ID_PAPI = 0
INSTALLATION_CLASS_NAMES = {YOLO_CLASS_ID_PAPI: "papi_installation"}
LAMP_STATE_CLASS_NAMES = {
    0: "papi_light_red",
    1: "papi_light_white",
}
LAMP_STATE_CLASS_IDS = {
    "red": 0,
    "white": 1,
}
# Default YOLO export taxonomy = installation-level (one box per 4-lamp PAPI cluster).
# The lamp-state (red/white) export path passes LAMP_STATE_CLASS_NAMES explicitly.
YOLO_CLASS_NAMES = INSTALLATION_CLASS_NAMES


def write_yolo_label(
    label_path: Path,
    class_id: int,
    bbox_xyxy_px: tuple[float, float, float, float],
    image_width: int,
    image_height: int,
) -> None:
    """Write a single-line YOLO label file: `class cx_norm cy_norm w_norm h_norm`."""
    write_yolo_labels(label_path, [(class_id, bbox_xyxy_px)], image_width, image_height)


def write_yolo_labels(
    label_path: Path,
    labels: list[tuple[int, tuple[float, float, float, float]]],
    image_width: int,
    image_height: int,
) -> None:
    """Write a YOLO label file with zero or more bbox rows."""
    if image_width <= 0 or image_height <= 0:
        raise ValueError(f"image dimensions must be positive, got {image_width}x{image_height}")
    lines: list[str] = []
    for class_id, bbox_xyxy_px in labels:
        x1, y1, x2, y2 = bbox_xyxy_px
        cx = (x1 + x2) / 2.0 / image_width
        cy = (y1 + y2) / 2.0 / image_height
        w = (x2 - x1) / image_width
        h = (y2 - y1) / image_height
        if not all(0.0 <= value <= 1.0 for value in (cx, cy, w, h)):
            raise ValueError(
                f"normalized YOLO coords out of [0, 1] for class {class_id}: "
                f"cx={cx:.6f} cy={cy:.6f} w={w:.6f} h={h:.6f} "
                f"(bbox {bbox_xyxy_px}, image {image_width}x{image_height})"
            )
        lines.append(f"{class_id} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")
    label_path.parent.mkdir(parents=True, exist_ok=True)
    label_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")

def write_data_yaml(yaml_path: Path, class_names: dict[int, str] | None = None) -> None:
    """Write the YOLO `data.yaml` descriptor used by Ultralytics-style trainers.

    ``class_names`` defaults to the installation taxonomy (the autolabel stage emits one
    installation box per frame); pass ``LAMP_STATE_CLASS_NAMES`` for a red/white per-lamp
    dataset so the descriptor matches the labels. The train/val/test paths are placeholders;
    sprint 2 will replace them with split-filtered file lists derived from configs/split.yaml.
    """
    if class_names is None:
        class_names = INSTALLATION_CLASS_NAMES
    names_block = "".join(f"  {class_id}: {name}\n" for class_id, name in sorted(class_names.items()))
    yaml_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_path.write_text(
        "# Auto-generated by workflows/scripts/pipeline.py (autolabel stage) -- replace train/val/test paths in sprint 2\n"
        "path: ../\n"
        "train: data/labels/auto\n"
        "val: data/labels/auto\n"
        "test: data/labels/auto\n"
        "names:\n" + names_block,
        encoding="utf-8",
    )
